export const spaces = [
  {
    id: 'ESP-101',
    category: 'Quincho',
    name: 'Quincho Los Aromos',
    capacity: 20,
    tarifa: '$35.000 CLP',
    tipo: 'Depósito',
    image: 'https://images.unsplash.com/photo-1560448204-444f743ef6e7?w=640&h=420&fit=crop&auto=format',
    description: 'Quincho equipado con parrilla y área de estar para reuniones familiares y sociales.',
    disponible: true,
    horario: '08:00 – 23:00',
    reglas: ['Máximo 20 personas', 'Depósito reembolsable en 5 días hábiles', 'Limpieza obligatoria al término', 'Sin música después de las 22:00'],
  },
  {
    id: 'ESP-102',
    category: 'Piscina',
    name: 'Piscina Techada',
    capacity: null,
    tarifa: 'Uso incluido',
    tipo: 'Sin costo',
    image: 'https://images.unsplash.com/photo-1613152184920-bc1c4ab7fd1d?w=640&h=420&fit=crop&auto=format',
    description: 'Piscina techada disponible todos los días. Temperatura regulada durante todo el año.',
    disponible: true,
    horario: '08:00 – 22:00',
    reglas: ['Ducha obligatoria antes de ingresar', 'Niños menores acompañados de adulto', 'No ingerir alimentos en el agua', 'Gorro de natación recomendado'],
  },
  {
    id: 'ESP-103',
    category: 'Salón de Eventos',
    name: 'Salón Mirador',
    capacity: 60,
    tarifa: '$60.000 CLP',
    tipo: 'Depósito',
    image: 'https://images.unsplash.com/photo-1759477274116-e3cb02d2b9d8?w=640&h=420&fit=crop&auto=format',
    description: 'Salón amplio con vista panorámica, ideal para eventos y celebraciones.',
    disponible: false,
    horario: '10:00 – 01:00',
    reglas: ['Capacidad máxima 60 personas', 'Decoración no estructural permitida', 'Catering externo autorizado', 'Reserva con 7 días de anticipación mínima'],
  },
  {
    id: 'ESP-104',
    category: 'Gimnasio',
    name: 'Sala de Musculación',
    capacity: null,
    tarifa: 'Uso incluido',
    tipo: 'Sin costo',
    image: 'https://images.unsplash.com/photo-1637430308606-86576d8fef3c?w=640&h=420&fit=crop&auto=format',
    description: 'Equipamiento completo de musculación y cardio disponible las 24 horas.',
    disponible: true,
    horario: '00:00 – 23:59',
    reglas: ['Ropa deportiva obligatoria', 'Toalla personal requerida', 'Limpiar equipos después de uso', 'Zapatos deportivos cerrados'],
  },
  {
    id: 'ESP-105',
    category: 'Cancha',
    name: 'Multicancha Techada',
    capacity: null,
    tarifa: '$15.000 CLP',
    tipo: 'Depósito',
    image: 'https://images.unsplash.com/photo-1785486249823-02fbb298c918?w=640&h=420&fit=crop&auto=format',
    description: 'Cancha techada habilitada para fútbol, básquetbol y actividades recreativas.',
    disponible: true,
    horario: '08:00 – 22:00',
    reglas: ['Calzado apropiado obligatorio', 'Sin alimentos en la cancha', 'Máximo 2 horas continuas por reserva', 'Cancelar con 24 hrs de anticipación'],
  },
  {
    id: 'ESP-106',
    category: 'Salón de Eventos',
    name: 'Sala de Juegos / Cowork',
    capacity: null,
    tarifa: '$10.000 CLP',
    tipo: 'Depósito',
    image: 'https://images.unsplash.com/photo-1774280898104-d329acaae7b7?w=640&h=420&fit=crop&auto=format',
    description: 'Espacio flexible para trabajo remoto, reuniones informales y entretenimiento.',
    disponible: true,
    horario: '08:00 – 22:00',
    reglas: ['Wifi de alta velocidad disponible', 'Capacidad máxima 15 personas', 'Silencio zona de trabajo', 'Equipos de juego de uso compartido'],
  },
  {
    id: 'ESP-107',
    category: 'Quincho',
    name: 'Quincho Terraza Norte',
    capacity: 12,
    tarifa: '$25.000 CLP',
    tipo: 'Depósito',
    image: 'https://images.unsplash.com/photo-1774281193052-2802571d87e7?w=640&h=420&fit=crop&auto=format',
    description: 'Quincho íntimo con vista al norte del condominio, perfecto para grupos pequeños.',
    disponible: true,
    horario: '08:00 – 22:00',
    reglas: ['Máximo 12 personas', 'Depósito reembolsable en 5 días hábiles', 'Uso exclusivo parrilla eléctrica', 'Respetar silencio nocturno'],
  },
]

export const gastos = [
  { item: 'Mantención de áreas comunes', mensual: '$180.000', anual: '$2.160.000', pct: 30, color: '#0D9488' },
  { item: 'Seguridad y conserjería', mensual: '$250.000', anual: '$3.000.000', pct: 42, color: '#005047' },
  { item: 'Servicios básicos (luz/aguas)', mensual: '$90.000', anual: '$1.080.000', pct: 15, color: '#14B8A6' },
  { item: 'Fondo de reserva', mensual: '$80.000', anual: '$960.000', pct: 13, color: '#99F6E4' },
]

// badge values: 'primary' | 'accent' | 'warning'
export const avisos = [
  {
    tipo: 'Asamblea',
    fecha: '22 ago 2026',
    titulo: 'Asamblea ordinaria de copropietarios',
    desc: 'Sala de Juegos / Cowork, 19:00 hrs. Orden del día: presupuesto 2027 y elección de comité.',
    badge: 'primary' as const,
    autor: 'Comité de Administración',
    confirmacion: true,
    confirmados: 34,
  },
  {
    tipo: 'Mantención',
    fecha: '25 ago 2026',
    titulo: 'Corte de agua programado',
    desc: 'Revisión de red de agua potable en Torres A y B. Duración estimada: 4 horas desde las 09:00.',
    badge: 'warning' as const,
    autor: 'Administración',
    confirmacion: false,
    confirmados: 0,
  },
  {
    tipo: 'Aviso',
    fecha: '18 ago 2026',
    titulo: 'Rifa solidaria — Bazar Comunidad',
    desc: 'Organizada por residentes del piso 8. Boletos disponibles en conserjería. Sorteo: 30 de agosto.',
    badge: 'accent' as const,
    autor: 'Residentes Piso 8',
    confirmacion: true,
    confirmados: 12,
  },
  {
    tipo: 'Aviso',
    fecha: '15 ago 2026',
    titulo: 'Nueva cámara de seguridad instalada',
    desc: 'Se instaló una nueva cámara en el acceso del estacionamiento subterráneo. Operativa desde el 15/08.',
    badge: 'accent' as const,
    autor: 'Administración',
    confirmacion: false,
    confirmados: 0,
  },
  {
    tipo: 'Mantención',
    fecha: '10 ago 2026',
    titulo: 'Fumigación de áreas comunes',
    desc: 'Proceso de fumigación preventiva programada para pasillos y sala de máquinas. Acceso restringido 6 hrs.',
    badge: 'warning' as const,
    autor: 'Comité de Administración',
    confirmacion: false,
    confirmados: 0,
  },
  {
    tipo: 'Asamblea',
    fecha: '5 ago 2026',
    titulo: 'Reunión extraordinaria — renovación ascensores',
    desc: 'Votación para aprobación de presupuesto de renovación de ascensores Torres C y D.',
    badge: 'primary' as const,
    autor: 'Comité de Administración',
    confirmacion: true,
    confirmados: 48,
  },
]

export const channels = [
  { area: 'Conserjería', resp: 'Conserje de turno', contacto: 'Interno 100', email: 'conserjeria@convivo.cl', horario: '24/7', urgencia: 'alta' },
  { area: 'Comité de administración', resp: 'Presidente del comité', contacto: '+56 9 1234 5678', email: 'comite@convivo.cl', horario: 'Lun–Vie 09:00–18:00', urgencia: 'media' },
  { area: 'Administración', resp: 'Administrador del condominio', contacto: '+56 9 8765 4321', email: 'admin@convivo.cl', horario: 'Lun–Vie 09:00–18:00', urgencia: 'media' },
  { area: 'Seguridad del sector', resp: 'Patrulla / Plan Cuadrante', contacto: 'Número específico del sector', email: null, horario: '24/7', urgencia: 'alta' },
  { area: 'Emergencias', resp: 'Carabineros / Bomberos / Ambulancia', contacto: '133 / 132 / 131', email: null, horario: '24/7', urgencia: 'critica' },
]

export const registroFotos = [
  {
    id: 'RF-001',
    titulo: 'Renovación sistema de riego — Jardín Central',
    categoria: 'Jardinería',
    fecha: '12 ago 2026',
    responsable: 'Verde Total SpA',
    monto: '$450.000 CLP',
    antes: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&auto=format',
    despues: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop&auto=format',
    estado: 'Completado',
    boleta: 'BOL-2026-0812',
  },
  {
    id: 'RF-002',
    titulo: 'Pintura de pasillos — Torre A (pisos 1–5)',
    categoria: 'Pintura',
    fecha: '5 ago 2026',
    responsable: 'Pinturas del Norte Ltda.',
    monto: '$280.000 CLP',
    antes: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&h=400&fit=crop&auto=format',
    despues: 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=600&h=400&fit=crop&auto=format',
    estado: 'Completado',
    boleta: 'BOL-2026-0805',
  },
  {
    id: 'RF-003',
    titulo: 'Mantención eléctrica sala de máquinas',
    categoria: 'Mantención eléctrica',
    fecha: '28 jul 2026',
    responsable: 'ElectroPro Chile',
    monto: '$195.000 CLP',
    antes: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&h=400&fit=crop&auto=format',
    despues: 'https://images.unsplash.com/photo-1558618047-3a3c7aae98ad?w=600&h=400&fit=crop&auto=format',
    estado: 'Completado',
    boleta: 'BOL-2026-0728',
  },
  {
    id: 'RF-004',
    titulo: 'Limpieza fachada principal',
    categoria: 'Limpieza de fachada',
    fecha: '20 jul 2026',
    responsable: 'Clean Masters SpA',
    monto: '$320.000 CLP',
    antes: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=600&h=400&fit=crop&auto=format',
    despues: 'https://images.unsplash.com/photo-1624204386084-dd8c05e32226?w=600&h=400&fit=crop&auto=format',
    estado: 'Completado',
    boleta: 'BOL-2026-0720',
  },
]

export const navLinks = [
  { label: 'Inicio', path: '/' },
  { label: 'Reservas', path: '/reservas' },
  { label: 'Gastos', path: '/gastos' },
  { label: 'Tablón', path: '/tablon' },
  { label: 'Dashboard', path: '/dashboard' },
  { label: 'Canales', path: '/canales' },
  { label: 'Registro', path: '/registro' },
]
